<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\MusicAlbums.Api\MusicAlbums.Api.csproj" />
    <ProjectReference Include="..\..\src\MusicAlbums.Core\MusicAlbums.Core.csproj" />
    <ProjectReference Include="..\..\src\MusicAlbums.Infrastructure\MusicAlbums.Infrastructure.csproj" />
    <ProjectReference Include="..\MusicAlbums.TestSupport\MusicAlbums.TestSupport.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
