apiVersion: v1
kind: Secret
metadata:
  name: musicalbums-secrets
  namespace: musicalbums
type: Opaque
stringData:
  AlbumProviders__Spotify__Mode: Api
  AlbumProviders__Spotify__ClientId: replace-me
  AlbumProviders__Spotify__ClientSecret: replace-me
